%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-robot-navigation
Version:        0.2.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS robot_navigation package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-costmap-queue
Requires:       ros-noetic-dlux-global-planner
Requires:       ros-noetic-dlux-plugins
Requires:       ros-noetic-dwb-critics
Requires:       ros-noetic-dwb-local-planner
Requires:       ros-noetic-dwb-msgs
Requires:       ros-noetic-dwb-plugins
Requires:       ros-noetic-global-planner-tests
Requires:       ros-noetic-locomotor
Requires:       ros-noetic-locomotor-msgs
Requires:       ros-noetic-locomove-base
Requires:       ros-noetic-nav-2d-msgs
Requires:       ros-noetic-nav-2d-utils
Requires:       ros-noetic-nav-core-adapter
Requires:       ros-noetic-nav-core2
Requires:       ros-noetic-nav-grid
Requires:       ros-noetic-nav-grid-iterators
Requires:       ros-noetic-nav-grid-pub-sub
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The robot_navigation package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed May 27 2020 David V. Lu!! <davidvlu@gmail.com> - 0.2.6-1
- Autogenerated by Bloom

